kind: Pod
apiVersion: v1
metadata:
  name: secret-injection-pod
spec:
  containers:
    - name: busybox-container
      image: busybox:1.37
      command: [ '/bin/sh', '-c', 'env && sleep 3600' ]
      volumeMounts:
        - name: db-cred
          mountPath: /etc/db-credentials
          readOnly: true

  volumes:
    - name: db-cred
      secret:
        secretName: db-credentials
        


          

