kind: Pod
apiVersion: v1
metadata:
  name: simple-pod
spec:
  containers:
  - name: test
    image: busybox:1.37
    command: ["/bin/sh", "-c", 'echo "Date:$(date)">>/data/message.txt; sleep 3600']
    volumeMounts:
      - mountPath: /data
        name: data-volume
  volumes:
    - name: data-volume
      emptyDir:
        sizeLimit: 500Mi


