kind: Deployment
apiVersion: apps/v1
metadata:
  name: php-apache
spec:
  selector:
    matchLabels:
      run: php-apache
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
        - name: hpa-container
          image: registry.k8s.io/hpa-example
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: 200m

