apiVersion: v1
kind: Pod
metadata:
  name: nginx-3-labels
  labels:
    app: nginx-prod-app
    environment: production
    team: devops

spec:
  containers:
    - name: nginx-prod
      image: nginx:latest
      ports:
        - containerPort: 80


