apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: capstone
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 3306

