kind: Pod
apiVersion: v1
metadata:
  name: startup-probe-pod
  labels:
    app: busybox
spec:
  containers:
    - name: busybox-container
      image: busybox:latest
      command: ["/bin/sh", "-c", "sleep 20 && touch /tmp/started; sleep 3600"]
      startupProbe:
        exec:
          command: [ "cat", "/tmp/started"]
        periodSeconds: 5
        failureThreshold: 2
      livenessProbe:
        exec:
          command: ["cat", "/tmp/started"]
        periodSeconds: 5
        failureThreshold: 3
